#!/usr/bin/env python3
"""JSON model tables → merged catalog.json + comptime catalog_data.zig.

Why not parse JSON at Zig comptime?
  Zig 0.16 `std.json` needs a real allocator; FixedBufferAllocator / page_allocator
  are not comptime-safe. So we freeze the table into Zig source at generate time.
  Runtime: pure `[]const ModelInfo` constants (true compile-time data).

Source of truth (edit these):
  packages/zag-ai/data/models/<provider>.json

Generated (do not hand-edit):
  packages/zag-ai/data/catalog.json      — tooling / review
  packages/zag-ai/src/catalog_data.zig   — @import by catalog.zig

Usage:
  python3 packages/zag-ai/scripts/generate_catalog.py
  python3 packages/zag-ai/scripts/generate_catalog.py --check
  python3 packages/zag-ai/scripts/generate_catalog.py --from-pi /path/to/pi/packages/ai --write-providers
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]  # packages/zag-ai
MODELS_DIR = ROOT / "data" / "models"
CATALOG_PATH = ROOT / "data" / "catalog.json"
ZIG_DATA_PATH = ROOT / "src" / "catalog_data.zig"

REQUIRED_MODEL_KEYS = ("id", "name", "context_window", "max_output_tokens")


def zig_string(s: str) -> str:
    out: list[str] = ['"']
    for c in s:
        o = ord(c)
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif c == "\n":
            out.append("\\n")
        elif c == "\r":
            out.append("\\r")
        elif c == "\t":
            out.append("\\t")
        elif o < 0x20:
            out.append(f"\\x{o:02x}")
        else:
            out.append(c)
    out.append('"')
    return "".join(out)


def load_provider_file(path: Path) -> list[dict[str, Any]]:
    doc = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        raise SystemExit(f"{path}: root must be object")
    provider = doc.get("provider") or path.stem
    models = doc.get("models")
    if not isinstance(models, list):
        raise SystemExit(f"{path}: models must be array")
    out: list[dict[str, Any]] = []
    for i, m in enumerate(models):
        if not isinstance(m, dict):
            raise SystemExit(f"{path}: models[{i}] must be object")
        for k in REQUIRED_MODEL_KEYS:
            if k not in m:
                raise SystemExit(f"{path}: models[{i}] missing {k}")
        flat: dict[str, Any] = {
            "id": m["id"],
            "name": m["name"],
            "provider": provider,
            "context_window": int(m["context_window"]),
            "max_output_tokens": int(m["max_output_tokens"]),
            "reasoning": bool(m.get("reasoning", False)),
            "vision": bool(m.get("vision", False)),
        }
        if "cost" in m and m["cost"] is not None:
            c = m["cost"]
            if not isinstance(c, dict):
                raise SystemExit(f"{path}: models[{i}].cost must be object")
            flat["cost"] = {
                "input": float(c.get("input", 0) or 0),
                "output": float(c.get("output", 0) or 0),
                "cache_read": float(c.get("cache_read", 0) or 0),
                "cache_write": float(c.get("cache_write", 0) or 0),
            }
        out.append(flat)
    return out


def merge_models_dir() -> list[dict[str, Any]]:
    if not MODELS_DIR.is_dir():
        raise SystemExit(f"missing {MODELS_DIR}")
    files = sorted(MODELS_DIR.glob("*.json"))
    if not files:
        raise SystemExit(f"no JSON files in {MODELS_DIR}")
    all_models: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for path in files:
        for m in load_provider_file(path):
            key = (m["provider"], m["id"])
            if key in seen:
                raise SystemExit(f"duplicate model {key[0]}/{key[1]} in {path}")
            seen.add(key)
            all_models.append(m)
    all_models.sort(key=lambda m: (m["provider"], m["id"]))
    return all_models


def catalog_doc(models: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "version": 1,
        "generated_note": "Merged by scripts/generate_catalog.py — edit data/models/*.json then re-run.",
        "models": models,
    }


def render_zig(models: list[dict[str, Any]]) -> str:
    lines: list[str] = [
        "//! AUTO-GENERATED by scripts/generate_catalog.py — do not edit by hand.",
        "//! Source: data/models/*.json → re-run: python3 packages/zag-ai/scripts/generate_catalog.py",
        "//!",
        "//! Compile-time model table (JSON maintained; frozen into Zig for comptime use).",
        "",
        "/// USD per 1M tokens.",
        "pub const CostRates = struct {",
        "    input: f64 = 0,",
        "    output: f64 = 0,",
        "    cache_read: f64 = 0,",
        "    cache_write: f64 = 0,",
        "",
        "    pub fn isZero(self: CostRates) bool {",
        "        return self.input == 0 and self.output == 0 and self.cache_read == 0 and self.cache_write == 0;",
        "    }",
        "};",
        "",
        "pub const ModelInfo = struct {",
        "    id: []const u8,",
        "    name: []const u8,",
        "    provider: []const u8,",
        "    context_window: u32,",
        "    max_output_tokens: u32,",
        "    reasoning: bool = false,",
        "    vision: bool = false,",
        "    cost: ?CostRates = null,",
        "};",
        "",
        f"/// {len(models)} models — frozen at compile time.",
        "pub const models: []const ModelInfo = &[_]ModelInfo{",
    ]
    for m in models:
        cost = m.get("cost")
        if cost:
            cost_lit = (
                f".{{ .input = {float(cost['input'])}, .output = {float(cost['output'])}, "
                f".cache_read = {float(cost['cache_read'])}, .cache_write = {float(cost['cache_write'])} }}"
            )
        else:
            cost_lit = "null"
        lines.append(
            "    .{{ .id = {id}, .name = {name}, .provider = {prov}, "
            ".context_window = {ctx}, .max_output_tokens = {mout}, "
            ".reasoning = {reason}, .vision = {vision}, .cost = {cost} }},".format(
                id=zig_string(m["id"]),
                name=zig_string(m["name"]),
                prov=zig_string(m["provider"]),
                ctx=int(m["context_window"]),
                mout=int(m["max_output_tokens"]),
                reason="true" if m.get("reasoning") else "false",
                vision="true" if m.get("vision") else "false",
                cost=cost_lit,
            )
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def write_outputs(models: list[dict[str, Any]]) -> None:
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    catalog_text = json.dumps(catalog_doc(models), indent=2, ensure_ascii=False) + "\n"
    CATALOG_PATH.write_text(catalog_text, encoding="utf-8")

    zig_text = render_zig(models)
    ZIG_DATA_PATH.write_text(zig_text, encoding="utf-8")

    n_prov = len({m["provider"] for m in models})
    print(f"wrote {CATALOG_PATH} ({len(models)} models, {n_prov} providers)")
    print(f"wrote {ZIG_DATA_PATH} (comptime table)")


def check_outputs(models: list[dict[str, Any]]) -> int:
    expected_json = json.dumps(catalog_doc(models), indent=2, ensure_ascii=False) + "\n"
    expected_zig = render_zig(models)
    ok = True
    if not CATALOG_PATH.is_file() or CATALOG_PATH.read_text(encoding="utf-8") != expected_json:
        print(f"stale or missing: {CATALOG_PATH}", file=sys.stderr)
        ok = False
    if not ZIG_DATA_PATH.is_file() or ZIG_DATA_PATH.read_text(encoding="utf-8") != expected_zig:
        print(f"stale or missing: {ZIG_DATA_PATH}", file=sys.stderr)
        ok = False
    if not ok:
        print("run: python3 packages/zag-ai/scripts/generate_catalog.py", file=sys.stderr)
        return 1
    print(f"ok: catalog up to date ({len(models)} models)")
    return 0


def try_import_pi(pi_ai: Path, prefer_pi: bool) -> dict[tuple[str, str], dict[str, Any]]:
    imported: dict[tuple[str, str], dict[str, Any]] = {}
    candidates: list[Path] = []
    data_dir = pi_ai / "src" / "providers" / "data"
    if data_dir.is_dir():
        candidates.extend(sorted(data_dir.glob("*.json")))
    prov_dir = pi_ai / "src" / "providers"
    if prov_dir.is_dir():
        candidates.extend(sorted(prov_dir.glob("*.json")))

    for path in candidates:
        if path.name.startswith("."):
            continue
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        provider = path.stem
        for m in flatten_pi_catalog(provider, raw):
            key = (m["provider"], m["id"])
            if key in imported and not prefer_pi:
                continue
            imported[key] = m
    return imported


def flatten_pi_catalog(provider: str, raw: Any) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []

    def add_model(m: dict[str, Any], prov: str) -> None:
        mid = m.get("id") or m.get("model")
        if not mid:
            return
        name = m.get("name") or mid
        ctx = m.get("context_window") or m.get("contextWindow") or 128_000
        max_out = m.get("max_output_tokens") or m.get("maxTokens") or 8_192
        reasoning = bool(m.get("reasoning", False))
        inputs = m.get("input") or []
        vision = bool(m.get("vision", False)) or (
            "image" in inputs if isinstance(inputs, list) else False
        )
        entry: dict[str, Any] = {
            "id": str(mid),
            "name": str(name),
            "provider": prov,
            "context_window": int(ctx),
            "max_output_tokens": int(max_out),
            "reasoning": reasoning,
            "vision": vision,
        }
        cost = m.get("cost")
        if isinstance(cost, dict):
            entry["cost"] = {
                "input": float(cost.get("input", 0) or 0),
                "output": float(cost.get("output", 0) or 0),
                "cache_read": float(cost.get("cache_read") or cost.get("cacheRead") or 0),
                "cache_write": float(cost.get("cache_write") or cost.get("cacheWrite") or 0),
            }
        out.append(entry)

    if isinstance(raw, list):
        for item in raw:
            if isinstance(item, dict):
                add_model(item, provider)
        return out

    if not isinstance(raw, dict):
        return out

    if "models" in raw and isinstance(raw["models"], list):
        prov = str(raw.get("provider") or provider)
        for item in raw["models"]:
            if isinstance(item, dict):
                add_model(item, prov)
        return out

    for key, group in raw.items():
        if key in ("provider", "version", "generated_note"):
            continue
        if isinstance(group, dict):
            if "id" in group or "contextWindow" in group or "context_window" in group:
                add_model(group, provider)
            else:
                for _, m in group.items():
                    if isinstance(m, dict):
                        add_model(m, provider)
        elif isinstance(group, list):
            for m in group:
                if isinstance(m, dict):
                    add_model(m, provider)
    return out


def write_provider_files(models: list[dict[str, Any]]) -> None:
    by_prov: dict[str, list[dict[str, Any]]] = {}
    for m in models:
        prov = m["provider"]
        entry = {k: v for k, v in m.items() if k != "provider"}
        by_prov.setdefault(prov, []).append(entry)
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    for prov, items in sorted(by_prov.items()):
        items.sort(key=lambda x: x["id"])
        doc = {"provider": prov, "models": items}
        path = MODELS_DIR / f"{prov}.json"
        path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"wrote {path} ({len(items)})")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if generated files are stale")
    ap.add_argument("--from-pi", type=Path, help="path to pi packages/ai for optional import")
    ap.add_argument("--prefer-pi", action="store_true", help="Pi rows override Zag on collision")
    ap.add_argument(
        "--write-providers",
        action="store_true",
        help="after --from-pi merge, rewrite data/models/*.json",
    )
    args = ap.parse_args()

    models = merge_models_dir()

    if args.from_pi:
        pi_ai = args.from_pi
        if not pi_ai.is_dir():
            print(f"--from-pi not a directory: {pi_ai}", file=sys.stderr)
            return 1
        imported = try_import_pi(pi_ai, prefer_pi=args.prefer_pi)
        if not imported:
            print("warning: no Pi model JSON found under", pi_ai, file=sys.stderr)
        else:
            by_key = {(m["provider"], m["id"]): m for m in models}
            for key, m in imported.items():
                if key in by_key and not args.prefer_pi:
                    continue
                by_key[key] = m
            models = sorted(by_key.values(), key=lambda m: (m["provider"], m["id"]))
            print(f"merged Pi import: {len(imported)} rows → {len(models)} total")
            if args.write_providers:
                write_provider_files(models)

    if args.check:
        return check_outputs(models)

    write_outputs(models)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
