#!/usr/bin/env python3
"""Score Zag docs for readability + security awareness; write quality reports.

Outputs (overwritten):
  docs/quality/readability-report.md
  docs/quality/security-report.md

Heuristics are intentionally simple and CI-stable — not a substitute for human review.

Usage:
  python3 scripts/score_docs.py
  python3 scripts/score_docs.py --root .
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

# Product Spec + Active + Quality (hand-written). Generated reports excluded from scoring.
SCORE_GLOBS = (
    "docs/vision.md",
    "docs/maturity.md",
    "docs/architecture.md",
    "docs/packaging.md",
    "docs/roadmap.md",
    "docs/INDEX.md",
    "docs/modules/*.md",
    "docs/phases/*.md",
    "docs/plan/*.md",
    "docs/decisions/active/*.md",
    "docs/decisions/complete/*.md",
    "docs/quality/evals.md",
    "docs/quality/contracts.md",
    "SECURITY.md",
    "AGENTS.md",
)

READABILITY_MARKERS = (
    ("has_h1", re.compile(r"^#\s+\S", re.M)),
    ("has_h2", re.compile(r"^##\s+\S", re.M)),
    ("has_code_or_table", re.compile(r"^```|^\|.+\|", re.M)),
    ("has_links", re.compile(r"\[[^\]]+\]\([^)]+\)")),
)

SECURITY_KEYWORDS = (
    "jail",
    "permission",
    "ask",
    "yolo",
    "shell-policy",
    "sandbox",
    "deny",
    "workspace",
    "relative path",
    "tool_error",
    "cancel",
    "secret",
    "credential",
    "security",
)

# Files that must mention at least one security concept when scored
SECURITY_CRITICAL = {
    "SECURITY.md",
    "docs/maturity.md",
    "docs/modules/permissions.md",
    "docs/modules/tools.md",
    "docs/quality/evals.md",
    "AGENTS.md",
}


def expand_globs(root: Path) -> list[Path]:
    files: list[Path] = []
    seen: set[Path] = set()
    for pattern in SCORE_GLOBS:
        for path in sorted(root.glob(pattern)):
            if path.is_file() and path not in seen:
                seen.add(path)
                files.append(path)
    return files


def readability_score(text: str) -> tuple[int, list[str]]:
    notes: list[str] = []
    score = 40  # baseline for existing markdown
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if not lines:
        return 0, ["empty"]

    for name, rx in READABILITY_MARKERS:
        if rx.search(text):
            score += 12
            notes.append(f"+{name}")
        else:
            notes.append(f"-missing_{name}")

    avg_len = sum(len(ln) for ln in lines) / max(len(lines), 1)
    if avg_len <= 100:
        score += 8
        notes.append("+line_length_ok")
    elif avg_len > 140:
        score -= 10
        notes.append("-long_lines")

    # Very long docs without structure
    if len(lines) > 400 and not re.search(r"^##\s+", text, re.M):
        score -= 15
        notes.append("-long_unstructured")

    return max(0, min(100, score)), notes


def security_score(rel: str, text: str) -> tuple[int, list[str]]:
    notes: list[str] = []
    lower = text.lower()
    hits = [kw for kw in SECURITY_KEYWORDS if kw in lower]
    if not hits:
        score = 20 if rel not in SECURITY_CRITICAL else 0
        notes.append("-no_security_keywords")
        if rel in SECURITY_CRITICAL:
            notes.append("-critical_file_weak")
        return score, notes

    score = 35 + min(50, 8 * len(hits))
    notes.append(f"+keywords:{len(hits)}")
    if rel in SECURITY_CRITICAL:
        score = min(100, score + 10)
        notes.append("+critical_coverage")
    # Penalize casual yolo without ask/default framing in critical docs
    if "yolo" in lower and "ask" not in lower and rel in SECURITY_CRITICAL:
        score -= 20
        notes.append("-yolo_without_ask")
    return max(0, min(100, score)), notes


def write_report(
    path: Path,
    title: str,
    rows: list[tuple[str, int, str]],
    overall: int,
    generated: str,
) -> None:
    lines = [
        f"# {title}",
        "",
        f"_Generated by `scripts/score_docs.py` on {generated}. Do not hand-edit scores._",
        "",
        f"**Overall: {overall}/100**",
        "",
        "| Path | Score | Notes |",
        "|------|------:|-------|",
    ]
    for rel, score, notes in rows:
        note_cell = notes.replace("|", "/")
        lines.append(f"| `{rel}` | {score} | {note_cell} |")
    lines.append("")
    lines.append("## How to interpret")
    lines.append("")
    lines.append("- Heuristic CI gate, not a human editorial grade.")
    lines.append("- Re-run: `python3 scripts/score_docs.py`")
    lines.append("- Layout lint: `python3 scripts/lint_docs.py`")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument("--min-readability", type=int, default=55)
    ap.add_argument("--min-security", type=int, default=50)
    ap.add_argument("--check", action="store_true", help="exit non-zero if below thresholds")
    args = ap.parse_args()
    root = args.root.resolve()
    generated = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    files = expand_globs(root)
    if not files:
        print("score_docs: no files matched", file=sys.stderr)
        return 1

    read_rows: list[tuple[str, int, str]] = []
    sec_rows: list[tuple[str, int, str]] = []
    read_sum = 0
    sec_sum = 0

    for path in files:
        rel = str(path.relative_to(root)).replace("\\", "/")
        text = path.read_text(encoding="utf-8", errors="replace")
        r_score, r_notes = readability_score(text)
        s_score, s_notes = security_score(rel, text)
        read_rows.append((rel, r_score, ", ".join(r_notes)))
        sec_rows.append((rel, s_score, ", ".join(s_notes)))
        read_sum += r_score
        sec_sum += s_score

    n = len(files)
    overall_r = round(read_sum / n)
    overall_s = round(sec_sum / n)

    write_report(
        root / "docs/quality/readability-report.md",
        "Docs readability report",
        read_rows,
        overall_r,
        generated,
    )
    write_report(
        root / "docs/quality/security-report.md",
        "Docs security-awareness report",
        sec_rows,
        overall_s,
        generated,
    )

    print(f"readability overall: {overall_r}/100 ({n} files)")
    print(f"security overall:    {overall_s}/100 ({n} files)")
    print("wrote docs/quality/readability-report.md")
    print("wrote docs/quality/security-report.md")

    if args.check:
        ok = True
        if overall_r < args.min_readability:
            print(f"FAIL readability {overall_r} < {args.min_readability}", file=sys.stderr)
            ok = False
        if overall_s < args.min_security:
            print(f"FAIL security {overall_s} < {args.min_security}", file=sys.stderr)
            ok = False
        # Critical files must not score 0 on security
        for rel, score, _ in sec_rows:
            if rel in SECURITY_CRITICAL and score < 40:
                print(f"FAIL critical security score {rel}={score} < 40", file=sys.stderr)
                ok = False
        return 0 if ok else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
